/**
 * Leather quality testing standards reference data.
 * Based on ISO, EN, ASTM and REACH/ECHA requirements used by major luxury and
 * performance leather brands (LVMH, Kering, Nike, Timberland, etc.)
 */

export interface QualityTest {
  id: string;
  standard: string;           // e.g. "ISO 11640"
  title: string;
  description: string;
  category: "fastness" | "chemical" | "physical" | "comfort";
  unit: string;               // e.g. "Grade (1–5)" or "mg/kg"
  passMark: string;           // e.g. "≥ 3/5" or "< 1.0"
  passValue: number;          // numeric pass threshold
  higherIsBetter: boolean;    // true = higher value passes
  typicalTarget: string;      // luxury-grade typical requirement
  brandRequirement?: string;  // e.g. "LVMH ≥ 4" or "Nike ≥ 3/5"
}

export const QUALITY_TESTS: QualityTest[] = [
  /* ── Colour Fastness ─────────────────────────────────────────────── */
  {
    id: "rub-dry",
    standard: "ISO 11640",
    title: "Rub Fastness — Dry",
    description: "Resistance of colour to dry rubbing on felt, rated by Grey Scale for staining.",
    category: "fastness",
    unit: "Grade (1–5)",
    passMark: "≥ 3/5",
    passValue: 3,
    higherIsBetter: true,
    typicalTarget: "≥ 4/5 (premium)",
    brandRequirement: "Kering: ≥ 4/5 · LVMH: ≥ 4/5",
  },
  {
    id: "rub-wet",
    standard: "ISO 11640",
    title: "Rub Fastness — Wet",
    description: "Resistance of colour to wet rubbing on felt, rated by Grey Scale for staining.",
    category: "fastness",
    unit: "Grade (1–5)",
    passMark: "≥ 2–3/5",
    passValue: 2,
    higherIsBetter: true,
    typicalTarget: "≥ 3/5 (premium)",
    brandRequirement: "Kering: ≥ 3/5 · LVMH: ≥ 3/5",
  },
  {
    id: "perspiration-acid",
    standard: "ISO 11641",
    title: "Perspiration Fastness — Acid",
    description: "Colour stability under simulated acid perspiration conditions.",
    category: "fastness",
    unit: "Grade (1–5)",
    passMark: "≥ 3/5",
    passValue: 3,
    higherIsBetter: true,
    typicalTarget: "≥ 4/5 (body-contact leathers)",
    brandRequirement: "Nike: ≥ 3/5 · Adidas: ≥ 3/5",
  },
  {
    id: "perspiration-alkaline",
    standard: "ISO 11641",
    title: "Perspiration Fastness — Alkaline",
    description: "Colour stability under simulated alkaline perspiration conditions.",
    category: "fastness",
    unit: "Grade (1–5)",
    passMark: "≥ 3/5",
    passValue: 3,
    higherIsBetter: true,
    typicalTarget: "≥ 4/5 (body-contact leathers)",
    brandRequirement: "Nike: ≥ 3/5 · Adidas: ≥ 3/5",
  },
  {
    id: "light-fastness",
    standard: "ISO 105-B02",
    title: "Light Fastness (Xenon Arc)",
    description: "Resistance to colour change on exposure to xenon arc light, rated on Blue Wool Scale.",
    category: "fastness",
    unit: "Grade (1–8)",
    passMark: "≥ 4/8",
    passValue: 4,
    higherIsBetter: true,
    typicalTarget: "≥ 5/8 (outdoor/automotive)",
    brandRequirement: "BMW/Mercedes automotive: ≥ 5 · Furniture: ≥ 4",
  },
  {
    id: "water-spotting",
    standard: "IUF 420",
    title: "Water Spotting Resistance",
    description: "Resistance to colour change and spot formation after water droplet contact.",
    category: "fastness",
    unit: "Grade (1–5)",
    passMark: "≥ 3/5",
    passValue: 3,
    higherIsBetter: true,
    typicalTarget: "≥ 4/5",
    brandRequirement: "Timberland: ≥ 3/5",
  },
  {
    id: "migration-pvc",
    standard: "ISO 15701",
    title: "Colour Migration to PVC",
    description: "Migration of dye from leather to PVC substrate under load and heat.",
    category: "fastness",
    unit: "Grade (1–5)",
    passMark: "≥ 3/5",
    passValue: 3,
    higherIsBetter: true,
    typicalTarget: "≥ 4/5 (automotive lining)",
    brandRequirement: "Automotive OEMs: ≥ 3/5",
  },

  /* ── Chemical Compliance ─────────────────────────────────────────── */
  {
    id: "ph",
    standard: "ISO 4045",
    title: "pH Value",
    description: "pH of the aqueous leather extract. Very low pH causes acid degradation; very high pH is discolouring.",
    category: "chemical",
    unit: "pH (3.5–7.5 target)",
    passMark: "3.5 – 6.5",
    passValue: 3.5,
    higherIsBetter: false,
    typicalTarget: "3.8 – 5.5 (optimal for chrome-tanned)",
    brandRequirement: "REACH: < 3.5 triggers ΔpH check",
  },
  {
    id: "chromium-vi",
    standard: "ISO 17234",
    title: "Extractable Cr(VI)",
    description: "Hexavalent chromium content — a potent allergen regulated across EU and global markets.",
    category: "chemical",
    unit: "mg/kg",
    passMark: "< 3 mg/kg",
    passValue: 3,
    higherIsBetter: false,
    typicalTarget: "< 1 mg/kg (luxury standard)",
    brandRequirement: "EU REACH Annex XVII: < 3 mg/kg · LVMH: 0 detected",
  },
  {
    id: "formaldehyde",
    standard: "ISO 17226",
    title: "Formaldehyde Content",
    description: "Free and partially hydrolysable formaldehyde — a sensitiser regulated in many markets.",
    category: "chemical",
    unit: "mg/kg",
    passMark: "< 150 mg/kg",
    passValue: 150,
    higherIsBetter: false,
    typicalTarget: "< 75 mg/kg (baby/child articles < 20 mg/kg)",
    brandRequirement: "Japan Law 112: < 75 mg/kg · EU: < 300 mg/kg",
  },
  {
    id: "azo-dyes",
    standard: "ISO 14362-1",
    title: "Restricted Azo Dyes",
    description: "Aromatic amines derived from azo dyes that can be carcinogenic. EU REACH banned list.",
    category: "chemical",
    unit: "mg/kg",
    passMark: "< 30 mg/kg per amine",
    passValue: 30,
    higherIsBetter: false,
    typicalTarget: "Not detectable",
    brandRequirement: "EU REACH Annex XVII: < 30 mg/kg · All major brands: not detected",
  },
  {
    id: "pah",
    standard: "ISO 16373-1",
    title: "Polycyclic Aromatic Hydrocarbons (PAH)",
    description: "PAHs are carcinogens found in certain carbon blacks and process oils used in leather finishing.",
    category: "chemical",
    unit: "mg/kg",
    passMark: "< 10 mg/kg (sum of 16 PAHs)",
    passValue: 10,
    higherIsBetter: false,
    typicalTarget: "< 2 mg/kg",
    brandRequirement: "EU REACH Annex XVII: < 1 mg/kg (benzo[a]pyrene < 0.5)",
  },
  {
    id: "pentachlorophenol",
    standard: "ISO 17070",
    title: "Pentachlorophenol (PCP)",
    description: "PCP is a biocide historically used in leather preservation; highly toxic and regulated.",
    category: "chemical",
    unit: "mg/kg",
    passMark: "< 5 mg/kg",
    passValue: 5,
    higherIsBetter: false,
    typicalTarget: "Not detectable (< 0.1 mg/kg)",
    brandRequirement: "EU REACH: < 5 mg/kg · Nike/Adidas RSL: not detected",
  },
  {
    id: "heavy-metals",
    standard: "ICP-MS / EN 71-3",
    title: "Heavy Metals (As, Cd, Pb, Hg…)",
    description: "Extractable heavy metals from pigments, dyes, and auxiliaries.",
    category: "chemical",
    unit: "mg/kg (Pb: < 90)",
    passMark: "Pb < 90 · Cd < 75 · As < 25",
    passValue: 90,
    higherIsBetter: false,
    typicalTarget: "Not detectable (toy safety EN 71-3 if applicable)",
    brandRequirement: "EU RoHS/REACH restrictions apply",
  },

  /* ── Physical / Mechanical ───────────────────────────────────────── */
  {
    id: "thickness",
    standard: "ISO 2589",
    title: "Thickness",
    description: "Measured under standard load; critical for product engineering and consistency.",
    category: "physical",
    unit: "mm",
    passMark: "± 0.1 mm of target",
    passValue: 0.1,
    higherIsBetter: false,
    typicalTarget: "Glove: 0.5–0.7 · Shoe upper: 1.0–1.8 · Belt: 3.5–5.0",
    brandRequirement: "Specified by brand",
  },
  {
    id: "tensile-strength",
    standard: "ISO 3376",
    title: "Tensile Strength",
    description: "Force per unit cross-section required to rupture a leather sample.",
    category: "physical",
    unit: "N/mm²",
    passMark: "≥ 10 N/mm²",
    passValue: 10,
    higherIsBetter: true,
    typicalTarget: "≥ 15 N/mm² (shoe uppers) · ≥ 10 N/mm² (garment)",
    brandRequirement: "ISO 17131: minimum per article type",
  },
  {
    id: "tear-strength",
    standard: "ISO 3377-2",
    title: "Tear Strength (Double Hole)",
    description: "Force required to propagate a tear through notched leather — indicator of durability.",
    category: "physical",
    unit: "N",
    passMark: "≥ 20 N",
    passValue: 20,
    higherIsBetter: true,
    typicalTarget: "≥ 30 N (shoe uppers) · ≥ 20 N (garment)",
    brandRequirement: "Specified by brand",
  },
  {
    id: "flexing-endurance",
    standard: "IUF 20 (Bally)",
    title: "Flexing Endurance",
    description: "Number of flex cycles before cracking or coating damage — critical for footwear and bags.",
    category: "physical",
    unit: "cycles",
    passMark: "≥ 50,000 (dry)",
    passValue: 50000,
    higherIsBetter: true,
    typicalTarget: "≥ 100,000 cycles (premium footwear)",
    brandRequirement: "Shoe uppers: ≥ 50,000 dry/20,000 wet",
  },
  {
    id: "shrink-temperature",
    standard: "ISO 3380",
    title: "Shrinkage Temperature (Ts)",
    description: "Temperature at which collagen fibres begin to contract — indicator of tanning completeness.",
    category: "physical",
    unit: "°C",
    passMark: "≥ 85 °C (chrome-tanned)",
    passValue: 85,
    higherIsBetter: true,
    typicalTarget: "Chrome: ≥ 100 °C · Veg: ≥ 85 °C · Wet-white: ≥ 80 °C",
    brandRequirement: "Typically ≥ 85 °C all articles",
  },

  /* ── Comfort & Biological ────────────────────────────────────────── */
  {
    id: "water-vapour",
    standard: "ISO 17229",
    title: "Water Vapour Permeability",
    description: "Rate of water vapour transmission through leather — key comfort metric for footwear/gloves.",
    category: "comfort",
    unit: "mg/(cm²·h)",
    passMark: "≥ 0.8",
    passValue: 0.8,
    higherIsBetter: true,
    typicalTarget: "≥ 1.5 (premium footwear interior)",
    brandRequirement: "EN ISO 20344 footwear: ≥ 0.8",
  },
  {
    id: "water-absorption",
    standard: "ISO 17229",
    title: "Water Vapour Absorption Capacity",
    description: "Total water absorbed by leather over 8 h — complementary comfort measure.",
    category: "comfort",
    unit: "mg/cm²",
    passMark: "≥ 25",
    passValue: 25,
    higherIsBetter: true,
    typicalTarget: "≥ 40 (gloves/liners)",
    brandRequirement: "EN ISO 20344: ≥ 25",
  },
  {
    id: "skin-sensitisation",
    standard: "ISO 11993",
    title: "Skin Sensitisation",
    description: "Assessment of potential skin sensitisation from leather extractables (cytocompatibility screening).",
    category: "comfort",
    unit: "Pass / Fail",
    passMark: "Pass",
    passValue: 1,
    higherIsBetter: true,
    typicalTarget: "Pass (required for all body-contact articles)",
    brandRequirement: "All LVMH, Kering brands: required",
  },
];

export function getTestsByCategory(category: QualityTest["category"]): QualityTest[] {
  return QUALITY_TESTS.filter((t) => t.category === category);
}

export const QUALITY_CATEGORIES: { id: QualityTest["category"]; label: string; color: string; bg: string }[] = [
  { id: "fastness",  label: "Colour Fastness",      color: "#7C3AED", bg: "#F5F3FF" },
  { id: "chemical",  label: "Chemical Compliance",   color: "#DC2626", bg: "#FEF2F2" },
  { id: "physical",  label: "Physical / Mechanical", color: "#D97706", bg: "#FFFBEB" },
  { id: "comfort",   label: "Comfort & Biological",  color: "#16A34A", bg: "#F0FDF4" },
];
